services:

  airsonic-advanced-app:
    image: docker.io/nfrastack/airsonic-advanced:latest
    container_name: airsonic-advanced-app
    labels:
      - traefik.enable=true
      - traefik.http.routers.airsonic.rule=Host(`airsonic.example.com`)
      - traefik.http.services.airsonic.loadbalancer.server.port=4040
    volumes:
      - ./config:/config
      - ./data/podcasts:/data/podcasts
      - ./data/music:/data/music
      - ./data/playlists:/data/playlists
    environment:
      - TIMEZONE=America/Vancouver

      - DB_TYPE=mariadb
      - DB_HOST=airsonic-advanced-db
      - DB_USER=airsonic
      - DB_NAME=airsonic
      - DB_PASS=airsonic
    networks:
      - proxy
      - services
    restart: always

  airsonic-advanced-db:
    image: docker.io/nfrastack/mariadb
    container_name: airsonic-advanced-db
    volumes:
      - ./db:/data
    environment:
      - TIMEZONE=America/Vancouver

      - ROOT_PASS=password
      - DB_NAME=airsonic
      - DB_USER=airsonic
      - DB_PASS=airsonic
    networks:
      - services
    restart: always

  airsonic-advanced-db-backup:
    container_name: airsonic-advanced-db-backup
    image: docker.io/tiredofit/db-backup
    volumes:
      - ./dbbackup:/backup
    environment:
      - TIMEZONE=America/Vancouver

      - DB01_HOST=airsonic-advanced-db
      - DB01_TYPE=mariadb
      - DB01_NAME=airsonic
      - DB01_USER=airsonic
      - DB01_PASS=airsonic
      - DB01_BACKUP_INTERVAL=1440
      - DB01_BACKUP_BEGIN=0000
      - DB01_CLEANUP_TIME=8640
    networks:
      - services
    restart: always

networks:
  proxy:
    external: true
  services:
    external: true
